android_binary(
    name = "android",
    custom_package = "io.github.izzyleung.zhihudailypurify",
    manifest = "//android/app:manifest",
    resource_files = [
        "//android/app:resource_files",
    ],
    deps = [
        "//android/app",
    ],
)
